# SPRING BOOT PROPERTIES
spring:

  # IDENTITY (ContextIdApplicationContextInitializer)
  application:
    name: springboot-multipile-data-source

  # PROFILES
  profiles:
    active: dev

  # JMX
  jmx:
    enabled: false

  # 优雅停机宽限期时间
  lifecycle:
    timeout-per-shutdown-phase: 30s

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------
server:
  port: 8080
  shutdown: graceful

# --------------
# Mybatis-Plus
# --------------
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
